blog_restaurant/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('restaurante.urls', namespace="restaurante")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurante/urls.py
from django.conf.urls import url, include
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = "restaurante"

urlpatterns = [

    path('', views.post_restaurant, name='post_restaurant'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout_page, name='logout'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('register', views.register, name='registro'),

    
    #Recuperar contraseña
    #path('', include('django.contrib.auth.urls')),
    #path('password_reset/', auth_views.PasswordChangeView.as_view()),
    #path(r'^password_reset/$', auth_views.password_reset, name= "password_reset"),
    #path('password_reset/done/', auth_views.password_reset_done, name= "password_reset_done"),
    #path('password_reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/', auth_views.password_reset_confirm, name= "password_reset_confirm"),
    #path('password_reset/complete', auth_views.password_reset_complete, name= "password_reset_complete"),
]

restaurante/models.py
from django.db import models

# Create your models here.
from django.utils import timezone  
from .data import TIPO_OPCIONES
from .data import SUR_AMERICA
from datetime import date
from django.contrib.auth.models import User

class PostRestaurant(models.Model):
    autor = models.ForeignKey(User, on_delete=models.PROTECT)
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_publicado = models.DateField(default=date.today)
    fecha_desactivado = models.DateField(blank=True, null=True)
    fecha_edicion = models.DateTimeField(auto_now=True)
    categoria = models.CharField(max_length=50, choices=TIPO_OPCIONES, default=SUR_AMERICA)
    tags = models.CharField(max_length=100, null=True, blank=True, default= 'tag')
    
    likes = models.ManyToManyField(User, related_name='likes', blank=True)


    def publicacion(self):
        self.fecha_publicado = timezone.now()
        self.save()

    def __str__(self):
        return self.titulo

    def total_likes(self):
        return self.likes.count()   

    #atribut shell, implicito manytomany
    def get_comentarios(self):
        return  self.comentario_set.all() 

class Comentario(models.Model):
    post_restaurant = models.ForeignKey(PostRestaurant, on_delete=models.CASCADE)
    comentarios = models.TextField(max_length=200, default='deja tu comentario aqui!', null=True)
    autor_comentario = models.ForeignKey(User, on_delete=models.PROTECT)
    fecha_comentario = models.DateField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.post_restaurant.titulo, str(self.post_restaurant.autor))
    

restaurante/forms.py
from django import forms
from .models import PostRestaurant, Comentario
from django.contrib.auth.models import User
import datetime

class RestauranteForm(forms.ModelForm):

    class Meta:
        model = PostRestaurant
        fields = ('titulo', 'texto','categoria','tags', 'fecha_publicado','fecha_desactivado',)
        widgets = {
            'fecha_publicado': forms.DateTimeInput(attrs={'type': 'date'}),
            'fecha_desactivado': forms.DateTimeInput(attrs={'type': 'date'}),
        }

class LoginForm(forms.Form):
	username= forms.CharField(label="Usuario")
	password = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
	
class RegistrationForm(forms.ModelForm):     
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'placeholder':'Ingrese contraseña aqui'}))
    confirm_password = forms.CharField(label=" Confirmar contraseña", widget=forms.PasswordInput(attrs={'placeholder':'Confirmar contraseña'}))
	
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')
 
    def clean_confirm_password(self):
        password=self.cleaned_data.get('password')	
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password	

class ComentarioForm(forms.ModelForm):
    comentarios = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Comenta aqui!'}), label="Comentario", required=False)

    class Meta:
        model = Comentario    
        fields = ('comentarios',)    

restaurante/views.py
from .models import PostRestaurant, Comentario
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from .forms import RestauranteForm,  LoginForm, RegistrationForm, ComentarioForm
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
# Create your views here.

def post_restaurant(request):
    # lt = less than  e= qual <= gt, lt, gte
    posts = PostRestaurant.objects.filter(
        Q(fecha_desactivado__isnull=True) | Q(fecha_desactivado__gte=timezone.now()),
        fecha_publicado__lte=timezone.now(),
        ).order_by('fecha_publicado').distinct().reverse() 
    query = request.GET.get('q')
    if query :
        posts = PostRestaurant.objects.filter(
        Q(categoria=query)|
        Q(tags__icontains=query)|    
        Q(autor__username__icontains=query), # post_contenido
        ).distinct()
    return render (request, 'restaurante/post_restaurant.html',{'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(PostRestaurant, pk=pk)
    comentarios = Comentario.objects.filter(post_restaurant=post).order_by('fecha_comentario').reverse()
    is_liked=False
    comentario_form = ComentarioForm()
    if request.user.is_authenticated :   
        like_user=post.likes.filter(
        username=request.user.username
        )
        if like_user.count()==1:
            is_liked=True
     
    if request.method == 'POST': 
        # {}, [], nm.get(.)
        form_is_like = request.POST.get("post_id")
        if form_is_like is not None:
            # cuando es like
            if is_liked == True:
                post.likes.remove(request.user)
            else:
                post.likes.add(request.user)
        else:
            comentario_form = ComentarioForm(request.POST)
            if comentario_form.is_valid():
                texto = request.POST.get('comentarios')
                if texto:
                    comentarios = Comentario.objects.create(
                        post_restaurant=post, 
                        autor_comentario=request.user,
                        comentarios=texto, 
                        fecha_comentario=timezone.now(),
                    )
                    comentarios.save()
                    return redirect('restaurante:post_detail', pk=post.pk)                

    context = {
    'post': post,
    'is_liked' : is_liked,
    'comentarios' : comentarios,
    'comentario_form': comentario_form,
    }    
    return render(request, 'restaurante/post_detail.html', context)

@login_required()
def post_new(request):
    if request.method == "POST":
        form = RestauranteForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            post.save()
            return redirect('restaurante:post_detail', pk=post.pk)
    else:
        form = RestauranteForm()
    return render(request, 'restaurante/post_edit.html', {'form': form})

# restringir con login
@login_required()
def post_edit(request, pk):
    # el user ya esta logueado 
    user = request.user
    post = get_object_or_404(PostRestaurant, pk=pk)
    if user == post.autor or user.is_superuser:
        if request.method == "POST":
            form = RestauranteForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.autor = request.user
                post.save()
                return redirect('restaurante:post_detail', pk=post.pk)
        # GET, PUT, DELETE, 
        else:
            form = RestauranteForm(instance=post)
            context = {
                'form': form,
            }    
        return render(request, 'restaurante/post_edit.html', context)    
    else:
        return redirect('restaurante:post_restaurant')


def login_page(request) :
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect('restaurante:post_restaurant')
            else:
                pass

    else:
        form = LoginForm()
    
    context ={
        'form': form
    }
    return render(request, 'restaurante/registro.html', context)

def logout_page(request):
    logout(request)
    return redirect('restaurante:post_restaurant')    

def register(request):
    if request.method == 'POST' :
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])    
            new_user.save()
            user = authenticate(username=new_user.username, password=form.cleaned_data['password'])
            login(request, user)
            return redirect('restaurante:post_restaurant')
    else:
        form = RegistrationForm()
    context = {
        'form' : form,
    }
    return render(request, 'registro/register.html', context)



@login_required()
def post_delete(request,pk):
    user = request.user               
    post = get_object_or_404(PostRestaurant, pk=pk)
    if user == post.autor or user.is_superuser:
        post.delete()
        return redirect('restaurante:post_restaurant')

restaurante/templates/restaurante/base.html
{% load static %}
<html>
    <head>
        <title>Blog restaurantes</title>
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

    </head>
    <body>
       {% include 'restaurante/navbar.html' %}
       
        <div class="page-header">
            <h1><a href="#" class="titlefirst"> ¡¡¡ Cuentanos tu experiencia gastronomica !!!</a></h1>
            
            {% if user.is_authenticated %}
            <a class="btn btn-warning" href="{% url 'restaurante:post_new' %}"><span class="glyphicon glyphicon-plus"></span>Crear Nuevo Post</a>
            {% endif %}
        </div>

        <div class="content-container">
            <div class="row">
                <div class="col-md-6"> 
                {% block content %}
                {% endblock %}
                <br>
                </div>  
            </div>  
        </div>

        <p class="introdu"> En este blog puedes describir tus experiencias gastronomicas. <br> Cuentanos que platos has probado en los diferentes restaurantes en que has estado y cuales nos recomiendas. 
        Primero <b> registrate </b> en nuestro blog o <b> ingresa </b> si ya tienes usuario, selecciona <b>CREAR NUEVO POST</b> e inspirate en tu escrito. Te invitamos a darle like a cada post que recomiendes. <br>
       

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


        {% block js %}
        {% endblock %}

        {% include 'restaurante/footer.html' %}
    </body>

</html>

restaurante/templates/restaurante/comentario_section.html
{% if request.user.is_authenticated %}
    <form method="POST">
    {% csrf_token %}
    {{ comentario_form.as_p }}
    <input type="submit" value="Enviar" class="btn btn-outline-success">
    </form>
{% endif %}
    <div id="comentario">
        {{ comentarios.count }} Comentarios {{ comentario | pluralize}}
        {% for comentario in post.get_comentarios %}
        <blockquote class="blockquote">
            <p class="mb-0">{{ comentario.comentarios }}</p>
            <footer class="blockquote-footer">Por: <cite title="Source Title"> {{comentario.autor_comentario|capfirst}}</cite> <br>  
            {{comentario.fecha_comentario}}</footer>
        </blockquote>    
        {% endfor %}    
    </div>

restaurante/templates/restaurante/footer.html
<footer class="footer">
	<p>Viaja por el mundo, conoce, comparte, aprende, disfruta y prueba tantos sabores y comidas. Luego comparte tu experiencia... </p>

</footer>

restaurante/templates/restaurante/like_section.html
{{ post.total_likes }} Like{{ post.total_likes|pluralize}}
{% if request.user.is_authenticated %}
    <form method="POST" href="{% url 'restaurante:post_detail' pk=post.pk %}">
        {% csrf_token %}
        {% if is_liked %}
            <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
        {% else %}
            <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
        {% endif %}
    </form>   
{% endif %}

restaurante/templates/restaurante/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Bienvenido</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'restaurante:post_restaurant' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="autor, tag o categoria" aria-label="Search" name='q'>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
      </ul>

      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hola!  {{ request.user }}</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'restaurante:login' %}">Login</a>
              <a class="dropdown-item" href="{% url 'restaurante:logout' %}">Logout</a>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'restaurante:login' %}" class="nav-link">Login</a>
          <li>    
          <li class="nav-item">
            <a href="{% url 'restaurante:registro' %}" class="nav-link">Registrarse</a>
          <li>   
         <!-- <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Registrarse</a>
          </div> -->
        </li>
        {% endif %}
      </ul>
    </div>
</nav>

restaurante/templates/restaurante/post_detail.html
{% extends 'restaurante/base.html' %}

{% block content %}
    <div class="post">
        {% if post.fecha_publicado %}
            <div class="date2">
                {{ post.fecha_publicado }}
            </div>
        {% endif %}
        {% if request.user == post.autor or user.is_superuser %}
        <a class="btn btn-outline-dark" href="{% url 'restaurante:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">Editar</span></a>

        <a class="btn btn-outline-danger" href="{% url 'restaurante:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">Borrar</span></a>
        {% endif %}
        
        <a class="btn btn btn-outline-dark" href="{% url 'restaurante:post_restaurant' %}">Regresar <span class="sr-only">(current)</span></a>


        
        <br><br>
        <h2>{{ post.titulo }}</h2>
        <p class="texto">{{ post.texto|linebreaksbr }}</p>
        <h4>Categoria : {{ post.categoria }}</h4>
        <h3>{{ post.autor }}</h3>
        

        <div id="like-section">
            {% include 'restaurante/like_section.html' %}
        </div>    

        <br><br>
        <hr>

        <div id="comentario-section">
        {% include 'restaurante/comentario_section.html' %}
        </div>  

        

    </div>
{% endblock %}

restaurante/templates/restaurante/post_edit.html
{% extends 'restaurante/base.html' %}

{% block content %}
    <h1>Nuevo post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-dark">Guardar</button>
    </form>
{% endblock %}

{% block js %}
    

{% endblock %}

restaurante/templates/restaurante/post_restaurant.html
{% extends 'restaurante/base.html' %}

{% block content %}
{% for post in posts %}
  <div class="img-thumbnail">
    <div class="post">
      <div class="date">
        {{ post.fecha_publicado }}
      </div>
      <h2><a class="titul" href="{% url 'restaurante:post_detail' post.pk %}">{{ post.titulo }}</a></h2>
      <div>
        <p class="texto">{{ post.texto|linebreaksbr }}</p>
      </div>  
      <div class="cat">
        Categoria: {{ post.categoria }}
      </div>
      <div class="tags">
        {{ post.tags }}
      </div>
      <div >
        {{ post.total_likes }} Like{{ post.total_likes|pluralize}}
      </div>

      <div class="autor">
       Autor: {{ post.autor }}
      </div>

      <br>

    </div>
  </div>  
{% endfor %}
{% endblock %}

restaurante/templates/restaurante/registro.html
{% extends 'restaurante/base.html' %}

{% block content %}
    <form method="POST">
    	{% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="save btn btn-outline-dark">Ingresar</button>
    </form>
{% endblock %}


<!--         <small>
    	<a href="{% url 'restaurante:password_reset' %}"> Olvidaste la contraseña?</a>
		</small> -->
        	